site_name: 'MPS Rocks'
site_url: 'http://mps.rocks'
site_description: 'A curated list of awesome MPS extensions/libraries, software and resources'
site_author: 'Kolja Dummann'
repo_name: 'coolya/mps.rocks'
repo_url: 'https://github.com/coolya/mps.rocks'
edit_uri: ''
theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'amber'
  feature:
    tabs: false
extra:
  social:
    - type: 'github'
      link: 'https://github.com/coolya'
    - type: 'twitter'
      link: 'https://twitter.com/dumdidum'
pages:
  - "Get yourself some MPS.": "index.md"
