name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
	pip install mkdocs
        pip install mkdocs-material
    - name: Test with pytest
      run: |
      git remote add gh-pages https://${{ secrets.GITHUB_TOKEN }}@github.com/coolya/mps.rocks.git
      mkdocs gh-deploy --clean -r gh-pages --force
